import { Download, FileText, Plus } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';

import Badge from '@/components/common/Badge';
import EmptyState from '@/components/common/EmptyState';
import LoadingSpinner from '@/components/common/LoadingSpinner';
import { get, getApiErrorMessage, post } from '@/services/api';
import { useAuth } from '@/store/AuthContext';
import type { Report } from '@/utils/types';

const ReportsPage = () => {
  const { user } = useAuth();
  const [reportType, setReportType] = useState<'weekly' | 'monthly' | 'custom'>('weekly');
  const [reports, setReports] = useState<Report[]>([]);
  const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    const loadReports = async () => {
      setLoading(true);
      setError('');

      try {
        const response = await get<Report[]>('/reports/');
        setReports(response);
      } catch (loadError) {
        setError(getApiErrorMessage(loadError, 'Unable to load reports.'));
      } finally {
        setLoading(false);
      }
    };

    void loadReports();
  }, []);

  const handleGenerate = async () => {
    setSubmitting(true);
    setError('');

    try {
      const generatedReport = await post<Report>('/reports/generate', { type: reportType, parameters: {} });
      setReports((current) => [generatedReport, ...current]);
    } catch (generateError) {
      setError(getApiErrorMessage(generateError, 'Unable to generate a report.'));
    } finally {
      setSubmitting(false);
    }
  };

  const selectedReport = useMemo(() => reports[0], [reports]);
  const getStatusVariant = (status: string) => {
    if (status === 'completed') return 'success';
    if (status === 'failed') return 'danger';
    if (status === 'running') return 'info';
    return 'warning';
  };

  return (
    <div className="grid gap-6 xl:grid-cols-[1.15fr_0.85fr]">
      <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div>
            <h1 className="text-xl font-semibold text-slate-900">Reports</h1>
            <p className="text-sm text-slate-500">Generate recurring intelligence packs for leadership and pursuit teams.</p>
          </div>

          <div className="flex flex-wrap items-center gap-3">
            <select
              value={reportType}
              onChange={(event) => setReportType(event.target.value as 'weekly' | 'monthly' | 'custom')}
              className="rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-900 outline-none focus:border-blue-500"
            >
              <option value="weekly">Weekly</option>
              <option value="monthly">Monthly</option>
              <option value="custom">Custom</option>
            </select>
            <button
              type="button"
              onClick={handleGenerate}
              disabled={submitting}
              className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2.5 text-sm font-semibold text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-70"
            >
              <Plus className="h-4 w-4" />
              {submitting ? 'Generating...' : 'Generate Report'}
            </button>
          </div>
        </div>

        {error ? <div className="mt-5 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">{error}</div> : null}

        <div className="mt-6">
          {loading ? (
            <LoadingSpinner label="Loading reports..." />
          ) : reports.length ? (
            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-slate-200 text-sm">
                <thead>
                  <tr className="text-left text-slate-500">
                    {['Title', 'Type', 'Status', 'Generated By', 'Created Date', 'Download'].map((column) => (
                      <th key={column} className="pb-3 font-medium">
                        {column}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {reports.map((report) => (
                    <tr key={report.id} className="text-slate-700">
                      <td className="py-4 pr-4 font-medium text-slate-900">{report.title ?? `${report.type} opportunity intelligence`}</td>
                      <td className="py-4 pr-4 capitalize">{report.type}</td>
                      <td className="py-4 pr-4">
                        <Badge text={report.status} variant={getStatusVariant(report.status)} size="md" />
                      </td>
                      <td className="py-4 pr-4">{report.generated_by ?? user?.full_name ?? 'System'}</td>
                      <td className="py-4 pr-4">{new Date(report.created_at).toLocaleString()}</td>
                      <td className="py-4">
                        <button
                          type="button"
                          disabled={!report.file_url}
                          className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
                        >
                          <Download className="h-4 w-4" />
                          Download
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          ) : (
            <EmptyState icon={FileText} title="No reports available" description="Generate a weekly, monthly, or custom report to begin building an intelligence archive." />
          )}
        </div>
      </section>

      <aside className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h2 className="text-lg font-semibold text-slate-900">Report Preview</h2>
        {selectedReport ? (
          <div className="mt-5 rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5">
            <p className="text-sm font-semibold text-slate-900">{selectedReport.title ?? `${selectedReport.type} opportunity intelligence`}</p>
            <p className="mt-2 text-sm leading-7 text-slate-600">
              Preview content will display executive summaries, priority pursuits, market shifts, and source health once report rendering is connected.
            </p>
          </div>
        ) : (
          <EmptyState icon={FileText} title="Preview unavailable" description="Select or generate a report to display the preview panel." />
        )}
      </aside>
    </div>
  );
};

export default ReportsPage;
